# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grid_world_pb2 as grid__world__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grid_world_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GWSimulationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoStep = channel.unary_unary(
                '/GWSimulation/DoStep',
                request_serializer=grid__world__pb2.GWActionRequest.SerializeToString,
                response_deserializer=grid__world__pb2.GWActionResponse.FromString,
                _registered_method=True)
        self.New = channel.unary_unary(
                '/GWSimulation/New',
                request_serializer=grid__world__pb2.GWNewRequest.SerializeToString,
                response_deserializer=grid__world__pb2.GWNewResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/GWSimulation/Reset',
                request_serializer=grid__world__pb2.GWResetRequest.SerializeToString,
                response_deserializer=grid__world__pb2.GWResetResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/GWSimulation/Close',
                request_serializer=grid__world__pb2.GWCloseRequest.SerializeToString,
                response_deserializer=grid__world__pb2.GWCloseResponse.FromString,
                _registered_method=True)


class GWSimulationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoStep(self, request, context):
        """Progress the simulation by specifying the actions to be taken by all drones.
        The client receives the new state of the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def New(self, request, context):
        """Start a new simulation by calling New.
        Sender will receive an id which uniquely identifies the simulation.
        Returns the initial state of the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset a current simulation by calling Reset.
        This should be equivalent to calling Close and New.
        Returns the initial state of the simulation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Closes a simulation and frees any resources it holds.
        This should be called when a simulation is done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GWSimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoStep': grpc.unary_unary_rpc_method_handler(
                    servicer.DoStep,
                    request_deserializer=grid__world__pb2.GWActionRequest.FromString,
                    response_serializer=grid__world__pb2.GWActionResponse.SerializeToString,
            ),
            'New': grpc.unary_unary_rpc_method_handler(
                    servicer.New,
                    request_deserializer=grid__world__pb2.GWNewRequest.FromString,
                    response_serializer=grid__world__pb2.GWNewResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=grid__world__pb2.GWResetRequest.FromString,
                    response_serializer=grid__world__pb2.GWResetResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=grid__world__pb2.GWCloseRequest.FromString,
                    response_serializer=grid__world__pb2.GWCloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GWSimulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GWSimulation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GWSimulation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GWSimulation/DoStep',
            grid__world__pb2.GWActionRequest.SerializeToString,
            grid__world__pb2.GWActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def New(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GWSimulation/New',
            grid__world__pb2.GWNewRequest.SerializeToString,
            grid__world__pb2.GWNewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GWSimulation/Reset',
            grid__world__pb2.GWResetRequest.SerializeToString,
            grid__world__pb2.GWResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GWSimulation/Close',
            grid__world__pb2.GWCloseRequest.SerializeToString,
            grid__world__pb2.GWCloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
