# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grid_world.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grid_world.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grid_world.proto\"V\n\x0cGWDroneState\x12\n\n\x02id\x18\x01 \x01(\x03\x12\t\n\x01x\x18\x02 \x01(\x03\x12\t\n\x01y\x18\x03 \x01(\x03\x12\x11\n\tdestroyed\x18\x04 \x01(\x08\x12\x11\n\tis_evader\x18\x05 \x01(\x08\"B\n\x07GWState\x12\x12\n\nterminated\x18\x01 \x01(\x08\x12#\n\x0c\x64rone_states\x18\x02 \x03(\x0b\x32\r.GWDroneState\"6\n\rGWDroneAction\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x19\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\t.GWAction\"D\n\x0fGWActionRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12%\n\rdrone_actions\x18\x02 \x03(\x0b\x32\x0e.GWDroneAction\"X\n\x10GWActionResponse\x12\x19\n\x05state\x18\x01 \x01(\x0b\x32\x08.GWStateH\x00\x12\x17\n\rerror_message\x18\x02 \x01(\tH\x00\x42\x10\n\x0estate_or_error\"\x1c\n\x0eGWResetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"*\n\x0fGWResetResponse\x12\x17\n\x05state\x18\x01 \x01(\x0b\x32\x08.GWState\"\x1c\n\x0eGWCloseRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\x11\n\x0fGWCloseResponse\"\x0e\n\x0cGWNewRequest\"4\n\rGWNewResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x17\n\x05state\x18\x02 \x01(\x0b\x32\x08.GWState*K\n\x08GWAction\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07NOTHING\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\x12\x06\n\x02UP\x10\x04\x12\x08\n\x04\x44OWN\x10\x05\x32\xc3\x01\n\x0cGWSimulation\x12/\n\x06\x44oStep\x12\x10.GWActionRequest\x1a\x11.GWActionResponse\"\x00\x12&\n\x03New\x12\r.GWNewRequest\x1a\x0e.GWNewResponse\"\x00\x12,\n\x05Reset\x12\x0f.GWResetRequest\x1a\x10.GWResetResponse\"\x00\x12,\n\x05\x43lose\x12\x0f.GWCloseRequest\x1a\x10.GWCloseResponse\"\x00\x42\x0f\xaa\x02\x0cGWSimulationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grid_world_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014GWSimulation'
  _globals['_GWACTION']._serialized_start=585
  _globals['_GWACTION']._serialized_end=660
  _globals['_GWDRONESTATE']._serialized_start=20
  _globals['_GWDRONESTATE']._serialized_end=106
  _globals['_GWSTATE']._serialized_start=108
  _globals['_GWSTATE']._serialized_end=174
  _globals['_GWDRONEACTION']._serialized_start=176
  _globals['_GWDRONEACTION']._serialized_end=230
  _globals['_GWACTIONREQUEST']._serialized_start=232
  _globals['_GWACTIONREQUEST']._serialized_end=300
  _globals['_GWACTIONRESPONSE']._serialized_start=302
  _globals['_GWACTIONRESPONSE']._serialized_end=390
  _globals['_GWRESETREQUEST']._serialized_start=392
  _globals['_GWRESETREQUEST']._serialized_end=420
  _globals['_GWRESETRESPONSE']._serialized_start=422
  _globals['_GWRESETRESPONSE']._serialized_end=464
  _globals['_GWCLOSEREQUEST']._serialized_start=466
  _globals['_GWCLOSEREQUEST']._serialized_end=494
  _globals['_GWCLOSERESPONSE']._serialized_start=496
  _globals['_GWCLOSERESPONSE']._serialized_end=513
  _globals['_GWNEWREQUEST']._serialized_start=515
  _globals['_GWNEWREQUEST']._serialized_end=529
  _globals['_GWNEWRESPONSE']._serialized_start=531
  _globals['_GWNEWRESPONSE']._serialized_end=583
  _globals['_GWSIMULATION']._serialized_start=663
  _globals['_GWSIMULATION']._serialized_end=858
# @@protoc_insertion_point(module_scope)
