# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import TDF_pb2 as TDF__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in TDF_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TDFSimulationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoStep = channel.unary_unary(
                '/TDFSimulation/DoStep',
                request_serializer=TDF__pb2.TDFDoStepRequest.SerializeToString,
                response_deserializer=TDF__pb2.TDFDoStepResponse.FromString,
                _registered_method=True)
        self.New = channel.unary_unary(
                '/TDFSimulation/New',
                request_serializer=TDF__pb2.TDFNewRequest.SerializeToString,
                response_deserializer=TDF__pb2.TDFNewResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/TDFSimulation/Reset',
                request_serializer=TDF__pb2.TDFResetRequest.SerializeToString,
                response_deserializer=TDF__pb2.TDFResetResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/TDFSimulation/Close',
                request_serializer=TDF__pb2.TDFCloseRequest.SerializeToString,
                response_deserializer=TDF__pb2.TDFCloseResponse.FromString,
                _registered_method=True)


class TDFSimulationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def New(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TDFSimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoStep': grpc.unary_unary_rpc_method_handler(
                    servicer.DoStep,
                    request_deserializer=TDF__pb2.TDFDoStepRequest.FromString,
                    response_serializer=TDF__pb2.TDFDoStepResponse.SerializeToString,
            ),
            'New': grpc.unary_unary_rpc_method_handler(
                    servicer.New,
                    request_deserializer=TDF__pb2.TDFNewRequest.FromString,
                    response_serializer=TDF__pb2.TDFNewResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=TDF__pb2.TDFResetRequest.FromString,
                    response_serializer=TDF__pb2.TDFResetResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=TDF__pb2.TDFCloseRequest.FromString,
                    response_serializer=TDF__pb2.TDFCloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TDFSimulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TDFSimulation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TDFSimulation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TDFSimulation/DoStep',
            TDF__pb2.TDFDoStepRequest.SerializeToString,
            TDF__pb2.TDFDoStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def New(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TDFSimulation/New',
            TDF__pb2.TDFNewRequest.SerializeToString,
            TDF__pb2.TDFNewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TDFSimulation/Reset',
            TDF__pb2.TDFResetRequest.SerializeToString,
            TDF__pb2.TDFResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TDFSimulation/Close',
            TDF__pb2.TDFCloseRequest.SerializeToString,
            TDF__pb2.TDFCloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
