# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ngw.v1 import ngw2d_pb2 as ngw_dot_v1_dot_ngw2d__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ngw/v1/ngw2d_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoStep = channel.unary_unary(
                '/ngw.v1.SimulationService/DoStep',
                request_serializer=ngw_dot_v1_dot_ngw2d__pb2.DoStepRequest.SerializeToString,
                response_deserializer=ngw_dot_v1_dot_ngw2d__pb2.DoStepResponse.FromString,
                _registered_method=True)
        self.New = channel.unary_unary(
                '/ngw.v1.SimulationService/New',
                request_serializer=ngw_dot_v1_dot_ngw2d__pb2.NewRequest.SerializeToString,
                response_deserializer=ngw_dot_v1_dot_ngw2d__pb2.NewResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/ngw.v1.SimulationService/Reset',
                request_serializer=ngw_dot_v1_dot_ngw2d__pb2.ResetRequest.SerializeToString,
                response_deserializer=ngw_dot_v1_dot_ngw2d__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/ngw.v1.SimulationService/Close',
                request_serializer=ngw_dot_v1_dot_ngw2d__pb2.CloseRequest.SerializeToString,
                response_deserializer=ngw_dot_v1_dot_ngw2d__pb2.CloseResponse.FromString,
                _registered_method=True)


class SimulationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoStep(self, request, context):
        """Progress the simulation by specifying the actions to be taken by all drones.
        The client receives the new state of the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def New(self, request, context):
        """Start a new simulation by calling New.
        Sender will receive an id which uniquely identifies the simulation.
        Returns the initial state of the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset a current simulation by calling Reset.
        This should be equivalent to calling Close and New.
        Returns the initial state of the simulation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Closes a simulation and frees any resources it holds.
        This should be called when a simulation is done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoStep': grpc.unary_unary_rpc_method_handler(
                    servicer.DoStep,
                    request_deserializer=ngw_dot_v1_dot_ngw2d__pb2.DoStepRequest.FromString,
                    response_serializer=ngw_dot_v1_dot_ngw2d__pb2.DoStepResponse.SerializeToString,
            ),
            'New': grpc.unary_unary_rpc_method_handler(
                    servicer.New,
                    request_deserializer=ngw_dot_v1_dot_ngw2d__pb2.NewRequest.FromString,
                    response_serializer=ngw_dot_v1_dot_ngw2d__pb2.NewResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=ngw_dot_v1_dot_ngw2d__pb2.ResetRequest.FromString,
                    response_serializer=ngw_dot_v1_dot_ngw2d__pb2.ResetResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=ngw_dot_v1_dot_ngw2d__pb2.CloseRequest.FromString,
                    response_serializer=ngw_dot_v1_dot_ngw2d__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ngw.v1.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ngw.v1.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngw.v1.SimulationService/DoStep',
            ngw_dot_v1_dot_ngw2d__pb2.DoStepRequest.SerializeToString,
            ngw_dot_v1_dot_ngw2d__pb2.DoStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def New(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngw.v1.SimulationService/New',
            ngw_dot_v1_dot_ngw2d__pb2.NewRequest.SerializeToString,
            ngw_dot_v1_dot_ngw2d__pb2.NewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngw.v1.SimulationService/Reset',
            ngw_dot_v1_dot_ngw2d__pb2.ResetRequest.SerializeToString,
            ngw_dot_v1_dot_ngw2d__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ngw.v1.SimulationService/Close',
            ngw_dot_v1_dot_ngw2d__pb2.CloseRequest.SerializeToString,
            ngw_dot_v1_dot_ngw2d__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
